### ISSUE TITLE
User "cog" menu isn't working properly when signed out

### ISSUE THREAD

**Issue by evansims** [ushahidi/crowdmap-issues#103]
You have to click the cog just right (specifically, just below it) for the user menu to pop up when logged out. Probably related to #44. Works fine once logged in. Reported by @heatherleson

**Comment by evansims** [comment]
Fixed

**Comment by heatherleson** [comment]
This issue is back, when signed in (same topic)

FF
http://dl.dropbox.com/u/34693557/Screenshots/fu.png
On the main crowdmap global home page and my individual landing 'heatherleson' page. I have tried clicking in the area all around the drop down icon.

**Comment by evansims** [comment]
Duplicate of ushahidi/crowdmap-issues#256
