### ISSUE TITLE
Location search freezes

### ISSUE THREAD

**Issue by heatherleson** [ushahidi/crowdmap-issues#152]
When trying to locate a place, the location search freezes in a loop. No location gets added to the post and you can't 'remove location' to start over. The options are: post with out a location or abandon the post. 

Steps:
Creating post. I first tried to search for "Kew Gardens London UK". the search did not locate. i hit the back button in the top left corner to start over. Click the location icon. 

Change the search to 
Royal Botanic Gardens  Kew Rd, Richmond, London, Surrey TW9 3AB.   The search also did not load. Hit "remove Location" to start over. Clicked the location icon. The previous search was still in the boxes. Hit enter, clicked on the box to change the location. No dice. clicked remove location, went back to post. Tried again. No dice.

Screen shot: http://dl.dropbox.com/u/34693557/Screenshots/ca.png

Browser - ff

The post without the location - https://crowdmap.com/post/584/kew-gardens-at-the-beginning-of-april-201?for_map_id=145

**Comment by evansims** [comment]
Fixed

**Comment by heatherleson** [comment]
This error is back.

Browser : FF
actions:
Add photo, click location, type in toronto canada, hit enter, http://dl.dropbox.com/u/34693557/Screenshots/cm.png.

This happened twice today. In order to get the post live, I have to start all over.

**Comment by brianherbert** [comment]
I see the issue. I'm going to open a new ticket for this since it isn't related. Heather, I'll ping you on it.
