### ISSUE TITLE
"Anonymous"/Default avatars don't show up in emails

### ISSUE THREAD

**Issue by evansims** [ushahidi/crowdmap-issues#94]
The API currently returns NULL when a user doesn't have a custom avatar setup and there is no gravatar registered to their primary address. I'll add a `?default=uri` parameter to the avatar endpoint to customize this behavior.

**Comment by evansims** [comment]
Fixed

**Comment by brianherbert** [comment]
I'm still seeing a broken image. The URL being linked in the HTML of the email looks like this:

```
https://api=
.crowdmap.com/v1/people/229/avatar/?default=3Dhttps%3A%2F%2Fcrowdmap.com%2F=
assets%2Fimg%2Fcontent%2Fanonymous.png
```

Here's the HTML

``` html
<img alt=3D"@gkamov is now following you=
 on Crowdmap!" style=3D"display: block; margin: 0 auto; width: 128px; heigh=
t: 128px; border: 5px solid #f5f5f5; border-radius: 6px" src=3D"https://api=
.crowdmap.com/v1/people/229/avatar/?default=3Dhttps%3A%2F%2Fcrowdmap.com%2F=
assets%2Fimg%2Fcontent%2Fanonymous.png" />
```

![screen shot 2013-04-30 at 10 11 29 pm](https://f.cloud.github.com/assets/106068/443994/8ce6bbee-b197-11e2-990a-ad03e81e4dbf.png)

**Comment by brianherbert** [comment]
Okay, that URL is wrong. Mail.app just showed me the URL with "=" at the end of every line.

This is the URL, which returns a 404 json response.

```
https://api.crowdmap.com/v1/people/229/avatar/?default=3Dhttps%3A%2F%2Fcrowdmap.com%2Fassets%2Fimg%2Fcontent%2Fanonymous.png
```

**Comment by evansims** [comment]
Huh... I don't know why the mail client would be putting "3D" behind every = in the HTML tags. It's definitely not that way in the template. O_o

**Comment by evansims** [comment]
OK, that's apparently a [quoted-printable](http://en.wikipedia.org/wiki/Quoted-printable) and email clients understand how to parse that. So, not the cause. Continuing to investigate. P.S. email clients are so weird.

**Comment by evansims** [comment]
Hm, I did some test emails and normal and default user avatars are loading properly for me in Gmail, Mall.app and elsewhere. Could Mail.app not have been set to display images from our servers?

**Comment by brianherbert** [comment]
I haven't done anything to Mail.app to restrict images from any given server. Sparrow and Gmail don't load them either. Even if I right click and "View image" it still shows up broken in both apps.

The images where it's not anonymous are displaying without any issues.

![screen shot 2013-05-01 at 11 09 39 am](https://f.cloud.github.com/assets/106068/447578/42164734-b204-11e2-8267-efd6022a41ff.png)

**Comment by evansims** [comment]
I only asked because I believe Mail.app ships with this setting disabled by default, but I could be wrong:

![screen_shot_2013-04-30_at_9 12 01_pm](https://f.cloud.github.com/assets/3093/447585/af169492-b204-11e2-8f53-f13203982208.png)

This might be related to gatekeeper since we host the anon graphic on the UI server sitting behind it. Are you signed into CM in Safari? I think they share cookies

**Comment by brianherbert** [comment]
Just checked, I have that setting selected. Also, I am on the new version of CM in Safari and I just tried restarting Mail.app, forcing a download of the image with no luck.

**Comment by evansims** [comment]
Not sure what else I can suggest. I can't reproduce the issue in any of my email client. Maybe you can do some hunting on this.

**Comment by brianherbert** [comment]
Hmm, it's broken on iOS for me too in Sparrow, Mail.app and Gmail.

This isn't the highest priority task. I'm going to move this to the Soon milestone.

**Comment by evansims** [comment]
Did you ever have any luck getting this to work? I still can't reproduce here. The email you forwarded me had a working image.

**Comment by brianherbert** [comment]
Still not working on any client or browser on any device I have handy.

**Comment by evansims** [comment]
Any news on this? Still happening to you?

**Comment by brianherbert** [comment]
I haven't seen it. Let's go ahead and close this and revisit if it crops up again.
